package models

const (
	TRXN_TRANCODE_CWD = "CWD"
	TRXN_TRANCODE_INQ = "INQ"
)

const (
	TRXN_STATUS_SUCCESS = 1
	TRXN_STATUS_FAIL    = 0
	TRXN_STATUS_CREATE  = 2
	TRXN_STATUS_SENT    = 3
)

const (
	PROTOCOL_TYPE_STANDARD       = 1
	PROTOCOL_TYPE_VISA_FRAME     = 2
	PROTOCOL_TYPE_ACK_CONTROLLER = 3
)
