server:
  address: ":9091"
  api_domain: ""
  api_prefix: ""
  enable_tls: false
  cert_file: "./cert/tmsapac.com.pfx"
  cert_password: "AF8032DABC311EE1F2E7D7DC1D0E0AB8"
db:
  driver: "sqlserver"
  server: "192.168.66.51"
  user: "7145F2BD073F752727FCAE75347929ED"
  password: "1E503BE39269F324D667CBD4A59FAA39"
  port: 1433
  database: "PayGreen_Dev_Hub"
